"""OPT-B Empirical Structural Language common contracts (ESLI-WP1).

Inactive deterministic conformance-only namespace. This package grants no active market
or selector authority, no canonical representation or family promotion, no semantic-promotion,
no Validation consumption, and no probability, risk, exposure, execution authority, or
agent-write authority. It fails closed at the ratified ESL boundary.
"""

from .model import (
    ComparabilityDomain,
    DependencyRef,
    DependencyRole,
    EvidenceFrontier,
    EvidenceState,
    ExecutionProfile,
    GenerationCorrespondence,
    OccurrenceAnchor,
    OccurrencePack,
    StructuralDimension,
    StructuralFacet,
    StructuralOccurrenceRecord,
)
from .soi_compat import (
    SOICompatibilityError,
    SOIFamilyAdapterBinding,
    SOITopologyEntry,
    TOPOLOGY_IDS,
    adapt_family_catalog,
    family_binding_from_mapping,
    invoke_soi_topology,
    topology_registry_from_mapping,
)
from .organisation_evidence import (
    OrganisationEvidenceError,
    apply_organisation_decision_rule_pack,
    assemble_organisation_evidence_set,
    assert_no_stable_organisation_claim_lawful,
    build_correspondence_edge,
    build_disagreement_record,
    build_invariant_evidence_record,
    build_metric_record,
    validate_decision_rule_pack_interface,
)
from .cei import (
    AST_NODE_TYPES,
    COMPARISON_DESIGNS,
    CONDITION_TYPES,
    CONSTRAINT_TARGETS,
    EVIDENCE_STATUSES,
    POPULATION_STATES,
    TEMPORAL_ROLES,
    CEIError,
    build_condition,
    build_constraint_evidence,
    build_contrast_spec,
    build_population_manifest,
    render_condition,
    validate_constraint_ast,
)
from .term_qualification import (
    ADMISSION_PROPOSAL_STATES,
    CHALLENGE_RECOMMENDATIONS,
    CHALLENGE_TARGETS,
    QUALIFICATION_DISPOSITIONS,
    QUALIFICATION_STAGES,
    TERM_CLASSES,
    TRANSPORT_STATUSES,
    TermQualificationError,
    build_language_candidate_binding,
    build_semantic_admission_proposal,
    build_structural_term_candidate,
    build_term_challenge,
    build_term_qualification_record,
    build_term_qualification_rule_pack,
    build_transport_candidate,
)
from .validators import ESLValidationError, validate_occurrence

__all__ = [
    "ComparabilityDomain",
    "DependencyRef",
    "DependencyRole",
    "EvidenceFrontier",
    "EvidenceState",
    "ExecutionProfile",
    "GenerationCorrespondence",
    "OccurrenceAnchor",
    "OccurrencePack",
    "StructuralDimension",
    "StructuralFacet",
    "StructuralOccurrenceRecord",
    "SOICompatibilityError",
    "SOIFamilyAdapterBinding",
    "SOITopologyEntry",
    "TOPOLOGY_IDS",
    "adapt_family_catalog",
    "family_binding_from_mapping",
    "invoke_soi_topology",
    "topology_registry_from_mapping",
    "OrganisationEvidenceError",
    "apply_organisation_decision_rule_pack",
    "assemble_organisation_evidence_set",
    "assert_no_stable_organisation_claim_lawful",
    "build_correspondence_edge",
    "build_disagreement_record",
    "build_invariant_evidence_record",
    "build_metric_record",
    "validate_decision_rule_pack_interface",
    "AST_NODE_TYPES",
    "COMPARISON_DESIGNS",
    "CONDITION_TYPES",
    "CONSTRAINT_TARGETS",
    "EVIDENCE_STATUSES",
    "POPULATION_STATES",
    "TEMPORAL_ROLES",
    "CEIError",
    "build_condition",
    "build_constraint_evidence",
    "build_contrast_spec",
    "build_population_manifest",
    "render_condition",
    "validate_constraint_ast",
    "ADMISSION_PROPOSAL_STATES",
    "CHALLENGE_RECOMMENDATIONS",
    "CHALLENGE_TARGETS",
    "QUALIFICATION_DISPOSITIONS",
    "QUALIFICATION_STAGES",
    "TERM_CLASSES",
    "TRANSPORT_STATUSES",
    "TermQualificationError",
    "build_language_candidate_binding",
    "build_semantic_admission_proposal",
    "build_structural_term_candidate",
    "build_term_challenge",
    "build_term_qualification_record",
    "build_term_qualification_rule_pack",
    "build_transport_candidate",
    "ESLValidationError",
    "validate_occurrence",
]
