from ovc.development.skills.cers.model import DispatchIdentity,QuiescenceControl,ReconciliationSnapshot,RunnableWorkItem,SupervisorCheckpoint
from ovc.development.skills.cers.reconcile import ReferenceReconciler
from ovc.development.skills.cers.runtime import DispatchCoordinator,EventLedger,FixtureExecutor,LeaseManager,failure_route,selective_invalidation

def snap(): return ReconciliationSnapshot("a"*40,"b"*40,({"programme_id":"P","status":"RUNNING"},),({"future_id":"F","status":"RUNNING"},))
def item(**o):
    b=dict(programme_id="P",packet_id="WP2",action="BUILD_FIXTURE_SUCCESSOR",priority=10,authority_class="AUTO_EXECUTABLE",authority_delta="NONE",prerequisites_pass=True,registered_root=True,executor_id="CERS_FIXTURE_EXECUTOR_V0_1",side_effect_class="REVERSIBLE_LOCAL"); b.update(o); return RunnableWorkItem(**b)
def test_deterministic_build_ahead():
    e=FixtureExecutor(); r=ReferenceReconciler(); xs=(item(packet_id="WP3",priority=20),item(packet_id="WP2",priority=10)); a=r.reconcile(snapshot=snap(),work_items=xs,executors={e.capability.executor_id:e.capability},quiescence=QuiescenceControl("RUN"),fencing_generation=1); b=r.reconcile(snapshot=snap(),work_items=reversed(xs),executors={e.capability.executor_id:e.capability},quiescence=QuiescenceControl("RUN"),fencing_generation=1); assert a.workset.workset_id==b.workset.workset_id; assert [x.packet_id for x in a.workset.items]==["WP2","WP3"]
def test_fail_closed():
    e=FixtureExecutor(); r=ReferenceReconciler(); out=r.reconcile(snapshot=snap(),work_items=(item(packet_id="A",registered_root=False),item(packet_id="B",executor_id="UNKNOWN"),item(packet_id="C",side_effect_class="IRREVERSIBLE_OR_UNKNOWN")),executors={e.capability.executor_id:e.capability},quiescence=QuiescenceControl("RUN"),fencing_generation=1); assert {x["packet_id"]:x["reason"] for x in out.workset.parked}=={"A":"UNREGISTERED_PROGRAMME_ROOT","B":"EXECUTOR_UNKNOWN_OR_INACTIVE","C":"IRREVERSIBLE_OR_UNKNOWN_SIDE_EFFECT"}
def test_hold_and_predecessor():
    e=FixtureExecutor(); r=ReferenceReconciler(); h=r.reconcile(snapshot=snap(),work_items=(item(),),executors={e.capability.executor_id:e.capability},quiescence=QuiescenceControl("HOLD"),fencing_generation=1); assert h.workset.parked[0]["reason"]=="QUIESCENCE_HOLD"; w=r.reconcile(snapshot=snap(),work_items=(item(predecessor_materialisation_required=True),),executors={e.capability.executor_id:e.capability},quiescence=QuiescenceControl("RUN"),fencing_generation=1); assert w.workset.parked[0]["reason"]=="PREDECESSOR_MATERIALISATION_REQUIRED"
def test_fence_duplicate_unknown_and_heartbeat():
    lm=LeaseManager(); old=lm.acquire("lane:P","a"); lease=lm.acquire("lane:P","b"); assert not lm.validate(old); e=FixtureExecutor(); c=DispatchCoordinator(lm,e); it=item(); d=DispatchIdentity("P",it.packet_id,it.action,it.work_id,e.capability.executor_id,lease.fencing_generation); a=c.dispatch(d,lease,QuiescenceControl("RUN")); b=c.dispatch(d,lease,QuiescenceControl("RUN")); assert a==b and len(e.starts)==1; assert e.heartbeat(d.dispatch_id,lease.fencing_generation).heartbeat_sequence==2; assert e.complete(d.dispatch_id,lease.fencing_generation).phase=="COMPLETED"; d2=DispatchIdentity("P","WPX",it.action,it.work_id,e.capability.executor_id,lease.fencing_generation); assert c.mark_unknown_start(d2,lease).phase=="DISPATCH_UNKNOWN"; assert c.reconcile_unknown(d2.dispatch_id).phase=="DISPATCH_UNKNOWN"
def test_event_ledger_quiescence_invalidation_checkpoint():
    l=EventLedger(); assert l.ingest(source="g",source_sequence=2,event={"state":"done"}); assert l.ingest(source="g",source_sequence=1,event={"state":"running"}); assert not l.ingest(source="g",source_sequence=1,event={"state":"running"}); assert [x["state"] for x in l.ordered()]==["running","done"]; e=FixtureExecutor(); assert e.capability.non_writing_fixture_only; assert selective_invalidation(changed_dependency="WP2",descendants=({"packet_id":"WP3","dependencies":["WP2"]},{"packet_id":"X","dependencies":["Y"]}))==("WP3",); assert failure_route("P","WP2")["cers_remediation_authority"]=="NONE"; assert SupervisorCheckpoint(1,chat_dependency_count=0).chat_dependency_count==0
