"""EC1 Post-Recurrence Scientific Challenge (PRSC) Research Operations namespace.

Research-only, non-authoritative challenge machinery. This package grants no market
or selector authority, no candidate-freeze or activation authority, no Validation or
publication authority, and no probability/risk/exposure/execution authority or
agent-write authority. Real-source PRSC challenge remains separately gated; missing
authority fails closed.
"""
from .contracts import CHALLENGE_DIMENSIONS, PRSCContractError, adapt_ec1_record, build_protocol_generation, semantic_id
from .dependence import DependenceGraphView, adapt_evidence_dependence_graph, build_candidate_dependence_profile, build_inference_block_manifest, leave_one_component_out
from .reference import build_negative_space_controls, build_reference_method_pack, dependency_preserving_block_resample, hac_ordered_secondary, validate_reference_preservation
from .representation import build_candidate_invariant_core, build_invariance_contract, build_population_crosswalk, build_representation_challenge_pack, directional_correspondence
from .temporal import build_context_challenge_pack, build_temporal_challenge_pack, build_temporal_context_stability_matrix, build_temporal_support_profile, leave_one_block_out_support, within_discovery_forward_support
from .boundary import build_boundary_challenge_pack, build_boundary_preserving_control, build_c2e_internal_variant_correspondence, build_episode_partition_correspondence, build_morphology_invariant_core, build_tolerance_contract, fit_blind_independent_segmentation, match_boundaries_one_to_one
from .multiplicity import build_hypothesis_family_registry, build_multiplicity_method_pack, build_shared_family_reference_draws, build_specification_opportunity_ledger, collapse_exact_semantic_duplicates, enforce_review_capacity, step_down_max_statistic_adjustment
from .algebra import build_candidate_freeze_recommendation, build_claim_dependency_manifest, build_counterevidence_completeness_record, build_scientific_challenge_vector, evaluate_scientific_disposition
from .adapters import bind_prsc_refs_to_candidate_review_card, bind_prsc_refs_to_question_decision, build_ec1_prsc_adapter_binding

__all__ = [name for name in globals() if not name.startswith("_")]
