from __future__ import annotations
import json, unittest
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
PACKET=ROOT/'artifacts/research_console_vnext/pvs3/RCN_RN_G4_GATE_PACKET.json'; DECISION=ROOT/'artifacts/research_console_vnext/pvs3/RCN_RN_G4_OPERATOR_DECISION.json'; RECON=ROOT/'artifacts/research_console_vnext/pvs3/RCN_RN_G4_POST_APPROVAL_RECONCILIATION.json'; STATE=ROOT/'registries/implementation/research_console_vnext/OVC_RCN_RN_STATE_v0_2.json'; CAND=ROOT/'registries/research_console_vnext/research_native/wp4a_investigate_binding_candidates_v1.json'; INV=ROOT/'registries/research_console_vnext/research_native/source_adapter_inventory_v2.json'
def load(p): return json.loads(p.read_text(encoding='utf-8'))
class RcnRnG4GateReady(unittest.TestCase):
 def test_consolidated_operator_packet_is_preserved_and_pass_recorded(self):
  g=load(PACKET); d=load(DECISION); r=load(RECON); self.assertEqual(g['gate_id'],'RCN-RN-G4'); self.assertEqual(g['gate_class'],'OPERATOR_REQUIRED'); self.assertEqual(g['recommended_decision'],'PASS'); self.assertEqual(g['decision_record'],'PENDING_OPERATOR_DECISION'); self.assertEqual(d['decision'],'PASS'); self.assertEqual(d['operator_instruction'],'OVC APPROVE RCN-RN-G4 PASS'); self.assertEqual(d['approved_gate_packet_blob_sha'],'374e1816d9b7ed243a54130cb24f5a128d8a6e41'); self.assertFalse(d['post_assurance_main_delta']['g4_candidate_set_changed']); self.assertEqual(d['granted_authority']['candidates'],['MARKET','C1','C2','C2E']); self.assertEqual(r['current_main'],'8f35ff9ee76eeb122eb1af66e9c166b0c45437cf'); self.assertFalse(r['main_advance']['g4_candidate_set_changed']); self.assertEqual(r['main_advance']['c2p_runtime_authority'],'NONE'); self.assertEqual(r['main_advance']['c2p_real_source_replay'],'DENIED_FUTURE_C2P2_RS0')
 def test_proposed_delta_matches_predeclared_owner_candidates_only(self):
  g=load(PACKET); c=load(CAND); inv=load(INV); proposed={x['capability_id'] for x in g['proposed_authority_delta']['candidates']}; declared={x['capability_id'] for x in c['candidates']}; self.assertEqual(proposed,declared); self.assertEqual(proposed,{'MARKET','C1','C2','C2E'}); excluded={x['capability_id'] for x in g['proposed_authority_delta']['excluded']}; self.assertEqual(excluded,{'C2P','C2_5','C3'}); census={x['capability_id']:x for x in inv['sources']}; self.assertEqual({k for k,v in census.items() if v['real_route']=='BOUND_G4_EXPLICIT_REAL_MODE'},{'opt_a','c1','c2','c2e'}); self.assertEqual('DENIED',census['c2p']['real_route']); self.assertEqual('DENIED',census['c2_5']['real_route']); self.assertEqual('DENIED',census['c3']['real_route']); self.assertFalse(census['c2p']['runtime_owner_materialized']); self.assertFalse(census['c3']['runtime_owner_materialized']); self.assertEqual('INACTIVE_REFERENCE',census['c3']['maturity'])
 def test_current_state_advances_after_g4_without_widening_g4_authority(self):
  s=load(STATE); self.assertEqual(s['packet_id'],'RCN-RN-POST-G4-SOURCE-BINDING'); self.assertIn(s['status'],{'APPROVED','COMPLETED'}); self.assertEqual(s['authority_required'],'AUTO_EXECUTABLE_WITHIN_G4_PASS'); self.assertEqual(s['authority_delta'],'NONE'); self.assertEqual(s['decision'],'PASS_DELEGATED_AUTO_RATIFICATION'); self.assertEqual(s['current_authority'],'G4_APPROVED_READ_ONLY_REAL_SOURCE_INVESTIGATE_PRESENTATION_MARKET_C1_C2_C2E'); self.assertEqual(s['real_source_routes'],'BOUND_EXPLICIT_REAL_MODE_MARKET_C1_C2_C2E__NO_FIXTURE_FALLBACK__OTHERS_DENIED'); self.assertEqual(s['operator_decision_record'],'artifacts/research_console_vnext/pvs3/RCN_RN_G4_OPERATOR_DECISION.json'); self.assertEqual(s['baseline_commit'],'1d963d5fe963ccf323caf013f9dade208a31345b'); self.assertEqual(s['blockers'],[])
 def test_scientific_and_upper_layer_firewalls_are_explicit(self):
  text=PACKET.read_text(encoding='utf-8')+DECISION.read_text(encoding='utf-8');
  for marker in ['NO_NEW_PROVIDER_INTAKE','NO_NEW_INSTRUMENT_MARKET_CLOCK_SIDE_OR_UNDECLARED_DEPENDENCY','NO_SELECTOR_THRESHOLD_MODEL_FAMILY_CANDIDATE_THEORY_SEMANTIC_ACTIVATION','NO_VALIDATION','NO_PUBLICATION','NO_PROBABILITY_RISK_EXPOSURE_TRADING_EXECUTION','C2.5 Candidate != EventOccurrence','C3 connectivity != entailment','C2P conformance namespace presence does not grant runtime or source authority']:
   self.assertIn(marker,text)
if __name__=='__main__': unittest.main()
