from __future__ import annotations
import importlib.util,json,unittest
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]; FIX=ROOT/'fixtures/research_console_vnext/console_pack_v0_1/c3_preparation.json'; MANIFEST=ROOT/'fixtures/research_console_vnext/console_pack_v0_1/manifest.json'; OPENAPI=ROOT/'fixtures/research_console_vnext/console_pack_v0_1/openapi_snapshot_v1.json'; INV=ROOT/'registries/research_console_vnext/research_native/source_adapter_inventory_v2.json'; STATE=ROOT/'registries/implementation/research_console_vnext/OVC_RCN_RN_STATE_v0_2.json'; ROUTES=ROOT/'registries/research_console_vnext/research_native/route_registry_v2.json'; SCHEMA=ROOT/'schemas/research_console_vnext/c3_preparation_v1.schema.json'; ADMISSION=ROOT/'artifacts/research_console_vnext/pvs3/PVS3_PHASE3_ADMISSION_RECORD.json'
def load(p): return json.loads(p.read_text(encoding='utf-8'))
class WP4DC3Preparation(unittest.TestCase):
 def test_census_distinguishes_inactive_reference_from_revised_runtime_owner_absence(self):
  f=load(FIX); c=next(x for x in load(INV)['sources'] if x['capability_id']=='c3'); self.assertTrue(c['repository_materialized']); self.assertEqual('src/ovc/opt_b/esl/c3_reference.py',c['source_path']); self.assertFalse(c['runtime_owner_materialized']); self.assertEqual('NONE',c['active_source_authority']); self.assertEqual('INACTIVE_REFERENCE',c['maturity']); self.assertEqual('DENIED',c['real_route']); self.assertEqual('NOT_MATERIALIZED',f['availability']); self.assertEqual([],f['nodes']); self.assertEqual([],f['edges']); self.assertEqual('PROHIBITED',f['semantic_synthesis'])
 def test_schema_manifest_route_and_openapi_keep_c3_fixture_only_while_other_g4_bindings_advance(self):
  schema=load(SCHEMA); manifest=load(MANIFEST); routes=load(ROUTES); openapi=load(OPENAPI); self.assertFalse(schema['additionalProperties']); self.assertEqual(0,schema['properties']['nodes']['maxItems']); self.assertEqual('PROHIBITED',schema['properties']['semantic_synthesis']['const']); self.assertEqual('FIXTURE_ONLY',manifest['mode']); self.assertEqual('GET_ONLY',routes['transport']); self.assertEqual('DENIED',routes['mutation_disposition']); self.assertEqual('BOUND_EXPLICIT_MODE_MARKET_C1_C2_C2E',routes['real_source_exposure']); self.assertNotIn('C3',routes['post_g4_binding']['capabilities']); self.assertFalse(routes['wp4d_preparation']['runtime_owner_materialized']); self.assertEqual('INACTIVE_REFERENCE',routes['wp4d_preparation']['reference_maturity']); self.assertEqual('PROHIBITED',routes['wp4d_preparation']['semantic_synthesis']); self.assertEqual(['get'],openapi['paths']['/api/v1/c3/graph']['methods']); self.assertEqual('FIXTURE_ONLY',openapi['mode'])
 def test_phase3_admission_is_historical_and_current_post_g4_state_preserves_decision(self):
  admission=load(ADMISSION); state=load(STATE); self.assertEqual('Begin Phase 3',admission['operator_instruction']); self.assertTrue(admission['g4_decision_not_implied_by_phase_admission']); self.assertEqual('NONE',admission['authority_delta_before_g4']); self.assertEqual('DENIED_UNTIL_RCN_RN_G4',admission['real_source_presentation']); self.assertEqual(611,admission['historical_wp4d_pr']); self.assertEqual('RCN-RN-POST-G4-SOURCE-BINDING',state['packet_id']); self.assertIn(state['status'],{'APPROVED','COMPLETED'}); self.assertEqual('AUTO_EXECUTABLE_WITHIN_G4_PASS',state['authority_required']); self.assertEqual('NONE',state['authority_delta']); self.assertEqual('PASS_DELEGATED_AUTO_RATIFICATION',state['decision']); self.assertEqual('artifacts/research_console_vnext/pvs3/RCN_RN_G4_OPERATOR_DECISION.json',state['operator_decision_record']); self.assertIn('MARKET_C1_C2_C2E',state['current_authority']); self.assertIn('OTHERS_DENIED',state['real_source_routes'])
 @unittest.skipIf(importlib.util.find_spec('fastapi') is None,'FastAPI dependency not installed')
 def test_runtime_is_empty_typed_absence_and_validation_is_denied_before_read(self):
  from fastapi.testclient import TestClient
  from apps.research_api.app import create_app
  app=create_app(); client=TestClient(app); before=app.state.fixture_store.resource_reads; denied=client.get('/api/v1/c3/graph?role=VALIDATION'); self.assertEqual(403,denied.status_code); self.assertEqual(before,app.state.fixture_store.resource_reads); p=client.get('/api/v1/c3/graph').json()['payload']; self.assertEqual('NOT_MATERIALIZED',p['availability']); self.assertEqual([],p['nodes']); self.assertEqual([],p['edges']); self.assertEqual('PROHIBITED',p['semantic_synthesis'])
if __name__=='__main__': unittest.main()
