import type { StylesheetJson } from "cytoscape";

export const atlasStyles: StylesheetJson = [
  {
    selector: "node",
    style: {
      "background-color": "#f7f8fa",
      "border-color": "#2b3038",
      "border-width": 2,
      color: "#17191d",
      label: "data(label)",
      "font-family": "Inter, Segoe UI, sans-serif",
      "font-size": 12,
      "font-weight": 600,
      height: 46,
      width: 124,
      shape: "round-rectangle",
      "text-halign": "center",
      "text-valign": "center",
      "text-wrap": "wrap",
      "text-max-width": "110px",
    },
  },
  { selector: "node[family = 'domain']", style: { shape: "rectangle", "background-color": "#e8eef6" } },
  { selector: "node[family = 'programme']", style: { shape: "round-rectangle", "border-width": 4, "background-color": "#e9f2e8" } },
  { selector: "node[family = 'service']", style: { shape: "barrel", "background-color": "#f3eadb" } },
  { selector: "node[family = 'record']", style: { shape: "tag", "background-color": "#ece8f3" } },
  { selector: "node[state = 'historical']", style: { opacity: 0.46, "border-style": "dashed" } },
  { selector: "node[state = 'reserved']", style: { "background-color": "#fff4cd", "border-style": "double", "border-width": 5 } },
  { selector: "node[state = 'conflict']", style: { "background-color": "#fff0e9", "border-color": "#8f2d16", "border-style": "dashed", "border-width": 5 } },
  { selector: ":parent", style: { "background-opacity": 0.08, "border-color": "#68717d", "border-style": "dashed", padding: "28px", "text-valign": "top" } },
  {
    selector: "edge",
    style: {
      width: 2,
      "line-color": "#69727d",
      "target-arrow-color": "#69727d",
      "target-arrow-shape": "triangle",
      "curve-style": "taxi",
      "taxi-direction": "rightward",
      "arrow-scale": 0.8,
    },
  },
  { selector: "edge[family = 'data']", style: { "line-color": "#2e6f78", "target-arrow-color": "#2e6f78" } },
  { selector: "edge[family = 'authority']", style: { "line-style": "dotted", width: 4, "line-color": "#474b52", "target-arrow-color": "#474b52" } },
  { selector: "edge[family = 'prohibition']", style: { "line-style": "dashed", width: 5, "line-color": "#9e2a2b", "target-arrow-color": "#9e2a2b", "target-arrow-shape": "tee" } },
  { selector: "edge[state = 'conflict']", style: { "line-style": "dashed", width: 5, "line-color": "#a54f20", "target-arrow-color": "#a54f20" } },
  { selector: "edge[state = 'historical']", style: { opacity: 0.35, "line-style": "dotted" } },
];
