"""RCCR is a Research Operations research-only, non-authoritative synthesis namespace.

It owns deterministic coverage/capability synthesis mechanics only. It grants no market,
selector, capability activation, scientific promotion, Validation, publication, execution authority,
or agent-write authority. Missing owner evidence or authority must fail closed.
"""

from .capability_frontier import (
    ACTIVATION_STATES,
    AUTHORITY_STATES,
    AVAILABILITY_STATES,
    DESIGN_STATES,
    IMPLEMENTATION_STATES,
    QUALIFICATION_STATES,
    CapabilityBinding,
    CapabilityBindingResolver,
    CapabilityFrontierCompiler,
    binding_state_digest,
)
from .core import (
    RCCRAppendOnlyStore,
    RCCRValidationError,
    canonical_json_bytes,
    logical_identity,
    validate_canonical_object,
)
from .need_review import (
    INDEPENDENCE_STATES,
    NEED_STATUSES,
    REVIEW_ROLES,
    VISIBILITY_CLASSES,
    CapabilityNeedEvaluator,
    HumanReviewLedger,
    ModeVisibilityFirewall,
    OffRegisterWorkaroundDetector,
    RCCRNeedReviewError,
)
from .pilot import (
    ADVERSARIAL_CASES,
    AV_EXPECTED,
    EC1_PILOT_QUESTIONS,
    GOLDEN_CASES,
    GOLDEN_EXPECTED,
    PilotAssuranceRunner,
    RCCRPilotError,
    bind_ec1_pilot_questions,
    fixture_authorship_actuals,
    pilot_review_load_summary,
    validate_fixture_currentness,
    validate_historical_counterfactual,
)
from .read_models import (
    RCCRReadModelError,
    assess_rate_comparison,
    build_capability_without_demand,
    build_pilot_exit_evidence_packet,
    build_portfolio_posture,
    query_read_model,
)
from .reference import (
    DIAGNOSTIC_PRECEDENCE,
    REFERENCE_RULE_PACK_ID,
    RCCRReferenceEngine,
    reference_replay_digest,
)
from .source_resolution import (
    DERIVATION_MODES,
    RequirementDependencyIndex,
    RequirementProfileCompiler,
    ResolvedSource,
    SourceResolverService,
    project_currentness,
)

__all__ = [
    "ACTIVATION_STATES",
    "ADVERSARIAL_CASES",
    "AUTHORITY_STATES",
    "AVAILABILITY_STATES",
    "AV_EXPECTED",
    "DESIGN_STATES",
    "DERIVATION_MODES",
    "DIAGNOSTIC_PRECEDENCE",
    "EC1_PILOT_QUESTIONS",
    "GOLDEN_CASES",
    "GOLDEN_EXPECTED",
    "IMPLEMENTATION_STATES",
    "INDEPENDENCE_STATES",
    "NEED_STATUSES",
    "QUALIFICATION_STATES",
    "REFERENCE_RULE_PACK_ID",
    "REVIEW_ROLES",
    "VISIBILITY_CLASSES",
    "CapabilityBinding",
    "CapabilityBindingResolver",
    "CapabilityFrontierCompiler",
    "CapabilityNeedEvaluator",
    "HumanReviewLedger",
    "ModeVisibilityFirewall",
    "OffRegisterWorkaroundDetector",
    "PilotAssuranceRunner",
    "RCCRAppendOnlyStore",
    "RCCRNeedReviewError",
    "RCCRPilotError",
    "RCCRReadModelError",
    "RCCRReferenceEngine",
    "RCCRValidationError",
    "RequirementDependencyIndex",
    "RequirementProfileCompiler",
    "ResolvedSource",
    "SourceResolverService",
    "assess_rate_comparison",
    "bind_ec1_pilot_questions",
    "binding_state_digest",
    "build_capability_without_demand",
    "build_pilot_exit_evidence_packet",
    "build_portfolio_posture",
    "canonical_json_bytes",
    "fixture_authorship_actuals",
    "logical_identity",
    "pilot_review_load_summary",
    "project_currentness",
    "query_read_model",
    "reference_replay_digest",
    "validate_canonical_object",
    "validate_fixture_currentness",
    "validate_historical_counterfactual",
]
