from __future__ import annotations

from enum import StrEnum


class EstimateState(StrEnum):
    ESTIMATED = "ESTIMATED"
    NO_ESTIMATE = "NO_ESTIMATE"
    NOT_EVALUABLE = "NOT_EVALUABLE"
    CENSORED = "CENSORED"


class OpportunityState(StrEnum):
    ESTIMATED = "ESTIMATED"
    NO_ESTIMATE = "NO_ESTIMATE"
    UNMATCHED = "UNMATCHED"
    AMBIGUOUS = "AMBIGUOUS"
    CENSORED = "CENSORED"
    NOT_EVALUABLE = "NOT_EVALUABLE"


class TemporalClass(StrEnum):
    OWNER_DEFINED_ONLINE_CAUSAL = "OWNER_DEFINED_ONLINE_CAUSAL"
    ONLINE_CAUSAL = "ONLINE_CAUSAL"
    CONFIRMATION_DELAYED = "CONFIRMATION_DELAYED"
    RETROSPECTIVE = "RETROSPECTIVE"
    CONTROL = "CONTROL"
    REFERENCE_ONLY = "REFERENCE_ONLY"


class Estimand(StrEnum):
    REFERENCE_BOUNDARY_AUDIT = "REFERENCE_BOUNDARY_AUDIT"
    CONSENSUS_BOUNDARY_DISCOVERY = "CONSENSUS_BOUNDARY_DISCOVERY"


class Sensitivity(StrEnum):
    METHOD_SENSITIVE = "METHOD_SENSITIVE"
    REPRESENTATION_SENSITIVE = "REPRESENTATION_SENSITIVE"
    CONTEXT_SENSITIVE = "CONTEXT_SENSITIVE"
    TRANSPORT_FAILURE = "TRANSPORT_FAILURE"


class FailureState(StrEnum):
    SOURCE_BINDING_INCOMPLETE = "SOURCE_BINDING_INCOMPLETE"
    C2E_REFERENCE_PACK_UNRESOLVED = "C2E_REFERENCE_PACK_UNRESOLVED"
    INPUT_PROJECTION_UNFROZEN = "INPUT_PROJECTION_UNFROZEN"
    SUPPORT_UNIVERSE_INCOMPLETE = "SUPPORT_UNIVERSE_INCOMPLETE"
    ASCERTAINMENT_FAIL = "ASCERTAINMENT_FAIL"
    SUPPORT_MISMATCH = "SUPPORT_MISMATCH"
    PARAMETER_MULTIPLICITY_FAIL = "PARAMETER_MULTIPLICITY_FAIL"
    ESTIMAND_CROSSING = "ESTIMAND_CROSSING"
    CAUSAL_ADMISSION_FAIL = "CAUSAL_ADMISSION_FAIL"
    CAPACITY_EXCEEDED = "CAPACITY_EXCEEDED"
    REPLAY_NONDETERMINISTIC = "REPLAY_NONDETERMINISTIC"
    CHECKPOINT_DIVERGENCE = "CHECKPOINT_DIVERGENCE"
    INVALID_GENERATION = "INVALID_GENERATION"
    DECISION_SEARCH_EXPOSURE_FAIL = "DECISION_SEARCH_EXPOSURE_FAIL"
    REPLICATION_CONTAMINATED = "REPLICATION_CONTAMINATED"
    INDEPENDENT_REVIEW_FAIL = "INDEPENDENT_REVIEW_FAIL"
    NO_STABLE_BOUNDARY_SUBSET = "NO_STABLE_BOUNDARY_SUBSET"


NON_TRANSITIVITY = (
    "BOUNDARY_ESTIMATE_NE_C2E_BOUNDARY",
    "METHOD_AGREEMENT_NE_INDEPENDENT_VOTES",
    "CONCORDANCE_NE_CAUSALITY",
    "LOCATION_STABILITY_NE_EPISODE_IDENTITY",
    "RETROSPECTIVE_BREAK_NE_FIRST_VALID_CAUSAL_BREAK",
    "OPERATOR_ANNOTATION_NE_GROUND_TRUTH",
    "METHOD_FAILURE_NE_INFORMATION_ABSENCE",
    "STABLE_SUBSET_NE_UNIVERSAL_SEGMENTATION",
    "BENCHMARK_PASS_NE_C2E_ACTIVATION",
)


CORE_COMPARATOR_IDS = ("B0", "B1", "B2", "B3", "B9")
CORE_TEMPORAL_DIVERSITY = (
    "OWNER_DEFINED_REFERENCE",
    TemporalClass.ONLINE_CAUSAL.value,
    TemporalClass.CONFIRMATION_DELAYED.value,
    TemporalClass.RETROSPECTIVE.value,
    TemporalClass.CONTROL.value,
)
