"""OVC Shared Systems v0.1 inactive/reference implementation only.

This package exposes Stage-0 bootstrap and the WP1-WP5 inactive identity,
envelope, replay, assurance, and exact-resolution reference machinery. It does not activate a Shared Systems runtime,
replace or restrict any current consumer path, create a new source/provider/research role, grant scientific or semantic
promotion, consume Validation, publish canon/R2, or grant probability, risk, exposure, execution, or agent-write authority.
Missing authority fails closed.
"""

from .stage0 import (
    BOOTSTRAP_NODES,
    NORMATIVE_EDGES,
    SharedSystemsStage0Error,
    build_stage0_proof,
    canonical_json_bytes,
    logical_hash,
    stage1_ready,
    verify_binding_registry,
)
from .identity import (
    AmbiguousIdentityBinding,
    HashAlgorithmDescriptor,
    IdentityProjection,
    IdentityRegistry,
    LegacySerializationBinding,
    NonCanonicalIdentityPayload,
    ProfileCollisionError,
    SerializationProfile,
    SharedIdentityError,
    UnknownIdentityBinding,
    canonicalize,
    load_registry,
    logical_identity,
    storage_bytes,
)
from .envelopes import (
    AdapterDescriptor,
    CompatibilityContract,
    DependencyDescriptor,
    EvidenceEntry,
    EvidenceFrontier,
    InterfaceBinding,
    LineageEdgeEnvelope,
    OwnerExtensionRegistry,
    SharedEnvelopeError,
    StatePlaneValue,
    StateVector,
    research_operations_legacy_state,
)
from .execution import (
    CapacityReceipt,
    CheckpointReceipt,
    ExecutionEnvironmentManifest,
    LogicalResultIdentity,
    ReplayResultManifest,
    RunExecutionManifest,
    RunSpecification,
    SemanticGenerationRef,
    SharedExecutionError,
    deterministic_partitions,
    reconcile_exact,
    run_reference,
)
from .assurance import (
    AssuranceAssertionResult, AssuranceAssertionSpec, AssurancePacket, AssuranceSuite,
    ChangeAssessment, ImpactDependencyEdge, IncidentRecord, InvalidationPlan,
    QualificationCurrentness, QualificationRecord, QuarantineRecord, ReplayObligation,
    SharedAssuranceError, build_invalidation_plan, deterministic_read_model,
    qualification_currentness,
)
from .resolution import (
    AdapterRegistry,
    CompatibilityRegistry,
    MigrationInventory,
    NonMigrationDecision,
    NonMigrationDecisionRegistry,
    RegistryDirectory,
    RegistryDirectoryEntry,
    ResolutionManifest,
    ResolutionRequest,
    ServiceConsumptionBinding,
    ServiceCurrentBinding,
    SharedExecutionContext,
    SharedResolutionError,
    SharedServiceDescriptor,
    resolve_exact,
)
from .foundation import (
    ArtifactReachability,
    DSAISecurityAdapterBinding,
    DurableArtifactDescriptor,
    EvidenceCommitManifest,
    EvidenceReachabilityManifest,
    ExternalArtifactReceipt,
    HealthAssertion,
    InformationExposureRecord,
    PILOT_HARD_FLOOR_DIMENSIONS,
    PILOT_NUMERIC_CAP_DIMENSIONS,
    PilotAcceptanceBudget,
    PilotBaselineMeasurement,
    SECURITY_FACTORS,
    SecurityDecisionRecord,
    SecurityRequest,
    ServiceHealthSnapshot,
    ServiceLevelObjective,
    SharedFoundationError,
    TelemetryRecord,
    build_evidence_commit_manifest,
    decide_security,
    inspect_reachability,
    reveal_protected_metadata,
)
from .dsai_shadow import (
    DSAIAdapterComplexityLedger,
    DSAIDualRunComparison,
    DSAIShadowError,
    DSAIShadowExecutionContext,
    DSAISharedSystemsConsumptionManifest,
    DSAISecurityRefusalParity,
    DSAISurfaceAdapterBinding,
    adapt_dsai_surface,
    compare_dsai_dual_run,
    compare_security_refusal,
    evaluate_adapter_complexity,
    unwrap_dsai_surface,
)
from .ro_dmrp_shadow import (
    REQUIRED_RECORD_TYPES,
    RODMRPAdapterComplexityLedger,
    RODMRPDualRunComparison,
    RODMRPEvidenceEvaluation,
    RODMRPReadOnlyArtifactBinding,
    RODMRPShadowAdapterBinding,
    RODMRPShadowError,
    RODMRPSharedSystemsConsumptionManifest,
    RODMRPStatePlaneCrosswalk,
    adapt_ro_record,
    build_read_only_artifact_binding,
    build_ro_evidence_frontier,
    compare_ro_dual_run,
    crosswalk_ro_state,
    evaluate_ro_adapter_complexity,
    inspect_read_only_artifacts,
    unwrap_ro_record,
)
from .esl_shadow import (
    ESLAdapterComplexityLedger,
    ESLEvidenceFrontierMapping,
    ESLReferenceComparison,
    ESLShadowError,
    ESLShadowSurfaceBinding,
    ESLSharedSystemsConsumptionManifest,
    ESL_SURFACES,
    adapt_esl_surface,
    compare_esl_reference,
    evaluate_esl_adapter_complexity,
    map_esl_evidence_frontier,
    unwrap_esl_surface,
)

__all__ = [
    "BOOTSTRAP_NODES",
    "NORMATIVE_EDGES",
    "SharedSystemsStage0Error",
    "build_stage0_proof",
    "canonical_json_bytes",
    "logical_hash",
    "stage1_ready",
    "verify_binding_registry",
    "AmbiguousIdentityBinding",
    "HashAlgorithmDescriptor",
    "IdentityProjection",
    "IdentityRegistry",
    "LegacySerializationBinding",
    "NonCanonicalIdentityPayload",
    "ProfileCollisionError",
    "SerializationProfile",
    "SharedIdentityError",
    "UnknownIdentityBinding",
    "canonicalize",
    "load_registry",
    "logical_identity",
    "storage_bytes",
    "AdapterDescriptor",
    "CompatibilityContract",
    "DependencyDescriptor",
    "EvidenceEntry",
    "EvidenceFrontier",
    "InterfaceBinding",
    "LineageEdgeEnvelope",
    "OwnerExtensionRegistry",
    "SharedEnvelopeError",
    "StatePlaneValue",
    "StateVector",
    "research_operations_legacy_state",
    "CapacityReceipt",
    "CheckpointReceipt",
    "ExecutionEnvironmentManifest",
    "LogicalResultIdentity",
    "ReplayResultManifest",
    "RunExecutionManifest",
    "RunSpecification",
    "SemanticGenerationRef",
    "SharedExecutionError",
    "deterministic_partitions",
    "reconcile_exact",
    "run_reference",
    "AssuranceAssertionResult", "AssuranceAssertionSpec", "AssurancePacket",
    "AssuranceSuite", "ChangeAssessment", "ImpactDependencyEdge", "IncidentRecord",
    "InvalidationPlan", "QualificationCurrentness", "QualificationRecord",
    "QuarantineRecord", "ReplayObligation", "SharedAssuranceError",
    "build_invalidation_plan", "deterministic_read_model", "qualification_currentness",
    "AdapterRegistry", "CompatibilityRegistry", "MigrationInventory",
    "NonMigrationDecision", "NonMigrationDecisionRegistry", "RegistryDirectory",
    "RegistryDirectoryEntry", "ResolutionManifest", "ResolutionRequest",
    "ServiceConsumptionBinding", "ServiceCurrentBinding", "SharedExecutionContext",
    "SharedResolutionError", "SharedServiceDescriptor", "resolve_exact",
    "ArtifactReachability", "DSAISecurityAdapterBinding",
    "DurableArtifactDescriptor", "EvidenceCommitManifest",
    "EvidenceReachabilityManifest", "ExternalArtifactReceipt",
    "HealthAssertion", "InformationExposureRecord",
    "PILOT_HARD_FLOOR_DIMENSIONS", "PilotAcceptanceBudget",
    "PILOT_NUMERIC_CAP_DIMENSIONS",
    "PilotBaselineMeasurement", "SECURITY_FACTORS", "SecurityDecisionRecord",
    "SecurityRequest", "ServiceHealthSnapshot", "ServiceLevelObjective",
    "SharedFoundationError", "TelemetryRecord", "build_evidence_commit_manifest",
    "decide_security", "inspect_reachability", "reveal_protected_metadata",
    "DSAIAdapterComplexityLedger", "DSAIDualRunComparison", "DSAIShadowError",
    "DSAIShadowExecutionContext", "DSAISharedSystemsConsumptionManifest",
    "DSAISecurityRefusalParity", "DSAISurfaceAdapterBinding", "adapt_dsai_surface",
    "compare_dsai_dual_run", "compare_security_refusal", "evaluate_adapter_complexity",
    "unwrap_dsai_surface",
    "REQUIRED_RECORD_TYPES", "RODMRPAdapterComplexityLedger",
    "RODMRPDualRunComparison", "RODMRPEvidenceEvaluation",
    "RODMRPReadOnlyArtifactBinding", "RODMRPShadowAdapterBinding",
    "RODMRPShadowError", "RODMRPSharedSystemsConsumptionManifest",
    "RODMRPStatePlaneCrosswalk", "adapt_ro_record",
    "build_read_only_artifact_binding", "build_ro_evidence_frontier",
    "compare_ro_dual_run", "crosswalk_ro_state",
    "evaluate_ro_adapter_complexity", "inspect_read_only_artifacts",
    "unwrap_ro_record",
    "ESLAdapterComplexityLedger", "ESLEvidenceFrontierMapping",
    "ESLReferenceComparison", "ESLShadowError", "ESLShadowSurfaceBinding",
    "ESLSharedSystemsConsumptionManifest", "ESL_SURFACES",
    "adapt_esl_surface", "compare_esl_reference",
    "evaluate_esl_adapter_complexity", "map_esl_evidence_frontier",
    "unwrap_esl_surface",
]
